# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow.resize(436, 378)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 71, 31))
        self.label_6.setObjectName("label_6")
        self.variety = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.variety.setGeometry(QtCore.QRect(110, 20, 311, 21))
        self.variety.setObjectName("variety")
        self.roast_degree = QtWidgets.QComboBox(parent=self.centralwidget)
        self.roast_degree.setGeometry(QtCore.QRect(110, 60, 311, 26))
        self.roast_degree.setObjectName("roast_degree")
        self.roast_degree.addItem("")
        self.roast_degree.addItem("")
        self.roast_degree.addItem("")
        self.shape = QtWidgets.QComboBox(parent=self.centralwidget)
        self.shape.setGeometry(QtCore.QRect(110, 110, 311, 26))
        self.shape.setObjectName("shape")
        self.shape.addItem("")
        self.shape.addItem("")
        self.taste_description = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.taste_description.setGeometry(QtCore.QRect(110, 160, 311, 51))
        self.taste_description.setObjectName("taste_description")
        self.price = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price.setGeometry(QtCore.QRect(110, 230, 151, 21))
        self.price.setObjectName("price")
        self.value = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.value.setGeometry(QtCore.QRect(110, 280, 113, 21))
        self.value.setObjectName("value")
        self.submit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(282, 310, 131, 32))
        self.submit_btn.setObjectName("submit_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add/edit"))
        self.label.setText(_translate("MainWindow", "Сорт"))
        self.label_2.setText(_translate("MainWindow", "Обжарка"))
        self.label_3.setText(_translate("MainWindow", "Форма"))
        self.label_4.setText(_translate("MainWindow", "Описание\n"
"вкуса"))
        self.label_5.setText(_translate("MainWindow", "Цена"))
        self.label_6.setText(_translate("MainWindow", "Объем\n"
"упаковки"))
        self.roast_degree.setItemText(0, _translate("MainWindow", "Слабая"))
        self.roast_degree.setItemText(1, _translate("MainWindow", "Средняя"))
        self.roast_degree.setItemText(2, _translate("MainWindow", "Сильная"))
        self.shape.setItemText(0, _translate("MainWindow", "Молотый"))
        self.shape.setItemText(1, _translate("MainWindow", "Зерновой"))
        self.submit_btn.setText(_translate("MainWindow", "Подтвердить"))
